default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  primary:
    <<: *default
    database: hermes_development
  cache:
    <<: *default
    database: hermes_development
  queue:
    <<: *default
    database: hermes_development

test:
  primary:
    <<: *default
    database: hermes_test
  cache:
    <<: *default
    database: hermes_test
  queue:
    <<: *default
    database: hermes_test

production:
  primary:
    <<: *default
  cache:
    <<: *default
  queue:
    <<: *default
